### ISSUE TITLE
Initialize project with Symphony template

### ISSUE THREAD

**Issue by WebDevJL** [Puzzlout/TrekToursApi#1]
@damirius  To start the API tasks when you are done with the flyer's tasks.

**Comment by damirius** [comment]
@WebDevJL @gsouvik 

Api project is set. I've added lots of stuff.
First off run `composer install`. If you aren't prompted to create parameters.yml, you can create one yourself. Copy one from other project or use parameters.yml.dist to setup database parameters.
After that you can run `php bin/console doctrine:database:create` to create database for api.
Also run `php bin/console doctrine:schema:update --force` to add `fos_user` table.
This should be it, I think I already configured everything else in config file. Set up your virtual host to api.trektours.dev or whatever you like and point to to the `/web/` directory just with the flyer website.

We have fosrest bundle, which provides us with easy way to make RESTful calls together with jms serializer for better data formatting.
You can see in `DefaultController` simple structure of the call.
We can just use annotations to specify the routes with `@Rest\Method("route.{_format}")`
Format is automatically set to json, but you can specify '.xml' if you wish to serve the data in the xml format. Actions are almost the same except we prefix them with method, for example, `getResourceAction`, where the resource is something we want to access. Also don't forget that for this to work we must extend `FOSRestController` instead of regular `Controller` class.
Serializer will automatically show only fields that we want to show when we setup serializer groups in entities and group in the call. I'll demonstrate that more when I create the entity and calls for customertinforequests.
I've also added FOSUserBundle which provides us with user tables which we can use for authentication together with JWT. JWT is installed but it isn't enabled yet. I'll do that later when we need to protect our calls.
We also use 2 bundles from nelmio, one is CORS bundle, which intercepts requests so that end users can access our api through Ajax calls without any problems.
And last but not least, we have Api Doc bundle from them, you can access api documentation by visiting `http://api.domain.dev/doc`. I'll add some annotations which ApiDoc reads and automatically generates documentation for each call when I create new calls for customerinforequests.
