### ISSUE TITLE
Add unit tests for each scenario endpoints

### ISSUE THREAD

**Issue by WebDevJL** [Puzzlout/TrekToursApi#7]
@damirius 

I tested the endpoints through the Sandbox but can you add the unit tests for each endpoints please?

Thanks.

**Comment by damirius** [comment]
@WebDevJL 

I've made one big functional test for customerinforequest endpoints. Keep in mind that Symfony automatically creates 'test' environment for both unit and functional testing. You'll see new parameters in `config_test.yml` which is used just for testing. Please create the database and tables like you did in regular environment. `php bin/console doctrine:database:create --env=test` and `php bin/console doctrine:schema:update --force --env=test` to create the db and add our tables.
After that everything is set, client created in tests is automatically in test environment. 
I've created a bunch of asserts to check status codes, content types, json format, ids and so on. There can always be more asserts if we wish. For example we can test each error exception and edge cases.
Also I've noticed while testing that if we add both `from` and `to` fields in get all listings query isn't working, so I fixed that.
One more thing, since we are using names for our routes I'm generating URLs through them, so even if we decide to change them again to something else tests will work, we just need to have fixed names.

**Comment by WebDevJL** [comment]
@damirius please look at the code style issues: https://www.codacy.com/app/Puzzlout/TrekToursApi/dashboard

Thanks.

**Comment by WebDevJL** [comment]
@damirius also, can you update the .travis_ci.yml file so the test passes: https://travis-ci.org/Puzzlout/TrekToursApi.

I think it is just a matter to enable the installation while the build is running.

Thanks

**Comment by damirius** [comment]
@WebDevJL 

I've setup travis correctly with the db, it should work now for tests.
As for code style issues, for CustomerInfoRequestsTest.php there are bunch of them saying that the code should be indented with 12 spaces instead of 8, but as far as I can see there aren't any code blocks there that should change indentation. Also my PHPStorm is setup for PSR2 so as far as code reformatting goes it is done automatically. Maybe I missed something?
Also it would be great to exclude everything but /src and /tests directories for this repo also and I think we could add exception for short variable names for `$id` if you think that's good idea.

**Comment by WebDevJL** [comment]
@damirius Ok to ignore issues with "id" but let's not generalize this. I see in some case where it could be a looong variable.

Move this issue to Code Review once you fixed all code style issues you can solve. Thanks.

**Comment by WebDevJL** [comment]
> @damirius said:
> Also it would be great to exclude everything but /src and /tests directories for this repo also and I think we could add exception for short variable names for $id if you think that's good idea.

I opened an issue to discuss that.

**Comment by WebDevJL** [comment]
@damirius is that done?

**Comment by damirius** [comment]
@WebDevJL 

Haven't seen this message, I believe this is done. We have currently ~95% coverage. I still need to test that part of post /customerinforequests endpoint where we are sending email which I will finish when we add email there actually (I tested it manually of course, code is working just need to write functional tests). Also there are few lines of code which aren't tested because I need to think how to recreate those cases in which they will trigger. I'll probably do that together with email testing when we come to that.
